// Copyright 2026 Muvon Un Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Compression anchor — persistent structured memory across compactions.
//!
//! The anchor is what survives every plan/conversation compaction in a
//! session. Instead of regenerating a summary from scratch each time the
//! window fills (the previous behavior), each compaction produces an
//! `AnchorUpdate` describing only what was new in the dropped span and
//! merges it into the existing `Anchor`. This preserves technical details
//! (file paths, error messages, decisions) across many compaction cycles.
//!
//! Reference: Factory.ai's "anchored iterative summarization" — measured
//! to retain technical detail more reliably than regenerate-each-pass.
//!
//! This module defines the data model and merge logic. Compaction wiring
//! lives in `src/mcp/core/plan/compression.rs` and the conversation
//! compression module — see those for how `extend()` is called.

use serde::{Deserialize, Serialize};

/// Persistent compaction anchor. Lives on `SessionInfo` and is updated on
/// every successful compaction. Empty-by-default — sessions that never
/// compact carry an empty anchor that costs nothing to serialize.
#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct Anchor {
	/// One-paragraph statement of what the session is trying to accomplish.
	/// Set on the first compaction, refined on subsequent ones.
	#[serde(default, skip_serializing_if = "String::is_empty")]
	pub intent: String,

	/// Concrete changes made (files modified, commands run, side effects).
	/// Append-only; deduplicated on insert.
	#[serde(default, skip_serializing_if = "Vec::is_empty")]
	pub changes_made: Vec<String>,

	/// Decisions reached and why. Survives indefinitely — the model needs
	/// these to stay coherent across long sessions.
	#[serde(default, skip_serializing_if = "Vec::is_empty")]
	pub decisions: Vec<String>,

	/// Files touched or read with content the model still needs to know
	/// about. Path strings, deduplicated.
	#[serde(default, skip_serializing_if = "Vec::is_empty")]
	pub file_refs: Vec<String>,

	/// Errors / failures encountered and how they were resolved (or not).
	#[serde(default, skip_serializing_if = "Vec::is_empty")]
	pub errors_seen: Vec<String>,

	/// What the session intended to do next at the time of compaction.
	/// Always overwritten by the latest update — older next-steps are
	/// stale by definition.
	#[serde(default, skip_serializing_if = "Vec::is_empty")]
	pub next_steps: Vec<String>,

	/// Number of compactions that have folded into this anchor.
	#[serde(default, skip_serializing_if = "is_zero")]
	pub compactions_folded: u32,

	/// Unix timestamp of the most recent compaction merged into this anchor.
	#[serde(default, skip_serializing_if = "is_zero_u64")]
	pub last_compacted_at: u64,
}

fn is_zero(n: &u32) -> bool {
	*n == 0
}
fn is_zero_u64(n: &u64) -> bool {
	*n == 0
}

/// Delta produced by a single compaction. Generated by an LLM
/// summarizing the dropped span; merged into `Anchor` via `extend`.
#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct AnchorUpdate {
	#[serde(default)]
	pub intent: Option<String>,
	#[serde(default)]
	pub changes_made: Vec<String>,
	#[serde(default)]
	pub decisions: Vec<String>,
	#[serde(default)]
	pub file_refs: Vec<String>,
	#[serde(default)]
	pub errors_seen: Vec<String>,
	#[serde(default)]
	pub next_steps: Vec<String>,
}

impl Anchor {
	/// Whether the anchor has any content. Used to decide between
	/// "first compaction" and "extend existing" formatting.
	pub fn is_empty(&self) -> bool {
		self.intent.is_empty()
			&& self.changes_made.is_empty()
			&& self.decisions.is_empty()
			&& self.file_refs.is_empty()
			&& self.errors_seen.is_empty()
			&& self.next_steps.is_empty()
	}

	/// Merge an update into this anchor. Append-only fields (`changes_made`,
	/// `decisions`, `file_refs`, `errors_seen`) are deduplicated on insert.
	/// `intent` is filled in on first set; subsequent updates only refine
	/// it if it was empty. `next_steps` always replaces (latest wins).
	pub fn extend(&mut self, update: AnchorUpdate, now_unix: u64) {
		if let Some(intent) = update.intent {
			let trimmed = intent.trim();
			if !trimmed.is_empty() && self.intent.is_empty() {
				self.intent = trimmed.to_string();
			}
		}

		extend_dedup(&mut self.changes_made, update.changes_made);
		extend_dedup(&mut self.decisions, update.decisions);
		extend_dedup(&mut self.file_refs, update.file_refs);
		extend_dedup(&mut self.errors_seen, update.errors_seen);

		// Latest next-steps win; older "what we plan to do" lines go stale.
		if !update.next_steps.is_empty() {
			self.next_steps = update.next_steps;
		}

		self.compactions_folded = self.compactions_folded.saturating_add(1);
		self.last_compacted_at = now_unix;
	}

	/// Render the anchor as a compact XML block suitable for inclusion in
	/// compressed-knowledge messages. XML over markdown: subsequent
	/// compressions re-feed this body as transcript input, and Claude is
	/// tuned to parse XML-delimited sections more reliably than markdown
	/// headers across paraphrase cycles.
	pub fn to_xml(&self) -> String {
		let mut out = String::with_capacity(512);
		if !self.intent.is_empty() {
			out.push_str("<intent>");
			out.push_str(self.intent.trim());
			out.push_str("</intent>\n");
		}
		render_list(&mut out, "decisions", "decision", &self.decisions);
		render_list(&mut out, "changes_made", "change", &self.changes_made);
		render_list(&mut out, "errors_seen", "entry", &self.errors_seen);
		render_list(&mut out, "file_references", "file", &self.file_refs);
		render_list(&mut out, "next_steps", "step", &self.next_steps);
		if self.compactions_folded > 0 {
			out.push_str(&format!("<folds>{}</folds>\n", self.compactions_folded));
		}
		out
	}
}

fn extend_dedup(target: &mut Vec<String>, additions: Vec<String>) {
	for item in additions {
		let trimmed = item.trim();
		if trimmed.is_empty() {
			continue;
		}
		if !target.iter().any(|existing| existing == trimmed) {
			target.push(trimmed.to_string());
		}
	}
}

fn render_list(out: &mut String, outer: &str, item: &str, items: &[String]) {
	let non_empty: Vec<&String> = items.iter().filter(|s| !s.trim().is_empty()).collect();
	if non_empty.is_empty() {
		return;
	}
	out.push_str(&format!("<{outer}>\n"));
	for v in non_empty {
		out.push_str(&format!("<{item}>{}</{item}>\n", v.trim(), item = item));
	}
	out.push_str(&format!("</{outer}>\n"));
}

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn default_anchor_is_empty() {
		let a = Anchor::default();
		assert!(a.is_empty());
		assert_eq!(a.compactions_folded, 0);
		assert_eq!(a.last_compacted_at, 0);
	}

	#[test]
	fn extend_records_first_intent_only() {
		let mut a = Anchor::default();
		a.extend(
			AnchorUpdate {
				intent: Some("Add feature X".to_string()),
				..Default::default()
			},
			100,
		);
		a.extend(
			AnchorUpdate {
				intent: Some("Now do feature Y instead".to_string()),
				..Default::default()
			},
			200,
		);
		// First-write-wins for intent — later updates don't overwrite.
		assert_eq!(a.intent, "Add feature X");
		assert_eq!(a.compactions_folded, 2);
		assert_eq!(a.last_compacted_at, 200);
	}

	#[test]
	fn extend_dedupes_appendable_lists() {
		let mut a = Anchor::default();
		a.extend(
			AnchorUpdate {
				decisions: vec!["use postgres".to_string(), "use redis".to_string()],
				..Default::default()
			},
			0,
		);
		a.extend(
			AnchorUpdate {
				decisions: vec!["use redis".to_string(), "use kafka".to_string()],
				..Default::default()
			},
			0,
		);
		assert_eq!(a.decisions, vec!["use postgres", "use redis", "use kafka"]);
	}

	#[test]
	fn extend_replaces_next_steps() {
		let mut a = Anchor::default();
		a.extend(
			AnchorUpdate {
				next_steps: vec!["write tests".to_string()],
				..Default::default()
			},
			0,
		);
		a.extend(
			AnchorUpdate {
				next_steps: vec!["ship it".to_string()],
				..Default::default()
			},
			0,
		);
		// Latest wins — old next-steps go stale.
		assert_eq!(a.next_steps, vec!["ship it"]);
	}

	#[test]
	fn extend_skips_empty_strings() {
		let mut a = Anchor::default();
		a.extend(
			AnchorUpdate {
				intent: Some("   ".to_string()),
				changes_made: vec!["".to_string(), "  ".to_string(), "real change".to_string()],
				..Default::default()
			},
			0,
		);
		assert!(a.intent.is_empty());
		assert_eq!(a.changes_made, vec!["real change"]);
	}

	#[test]
	fn to_xml_renders_only_present_sections() {
		let mut a = Anchor::default();
		a.extend(
			AnchorUpdate {
				intent: Some("Refactor auth".to_string()),
				decisions: vec!["use JWT".to_string()],
				..Default::default()
			},
			0,
		);
		let xml = a.to_xml();
		assert!(xml.contains("<intent>Refactor auth</intent>"));
		assert!(xml.contains("<decisions>"));
		assert!(xml.contains("<decision>use JWT</decision>"));
		// Empty sections are skipped.
		assert!(!xml.contains("<errors_seen"));
		assert!(!xml.contains("<next_steps"));
	}

	#[test]
	fn empty_anchor_renders_to_short_string() {
		let a = Anchor::default();
		let xml = a.to_xml();
		assert!(xml.is_empty() || xml.len() < 50);
	}

	#[test]
	fn json_round_trip_preserves_state() {
		let mut a = Anchor::default();
		a.extend(
			AnchorUpdate {
				intent: Some("test intent".to_string()),
				decisions: vec!["d1".to_string()],
				file_refs: vec!["a/b.rs".to_string()],
				..Default::default()
			},
			42,
		);
		let json = serde_json::to_string(&a).expect("serialize");
		let restored: Anchor = serde_json::from_str(&json).expect("deserialize");
		assert_eq!(restored.intent, "test intent");
		assert_eq!(restored.decisions, vec!["d1"]);
		assert_eq!(restored.file_refs, vec!["a/b.rs"]);
		assert_eq!(restored.last_compacted_at, 42);
		assert_eq!(restored.compactions_folded, 1);
	}
}
